;*******************************************************************************
;    GLOBAL CONFIGURATION                                                      *
;*******************************************************************************
#ifndef GLOBAL_INC
    
    ; 20MHz external oscillator, 115200 baud rate USART (otherwise 9600)
    #define EXTERNAL_CLOCK
    
    ; B6, B7 disabled
    #define PROGRAMMER
    
#define GLOBAL_INC
#endif

